### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by JasonBenfrin** [hartontw/aternosAPI#1]
I got this error **"No node found for selector: #user"**. So I turned headless to false. And I get this error from Aternos "**Sorry, an error occurred!**" with *ID: 403*. I've seen the same issue on other repositories too and they can't fix it either.
![image](https://user-images.githubusercontent.com/86666641/146675507-347e992b-d6f1-448e-b308-2e5223f80e07.png)
![image](https://user-images.githubusercontent.com/86666641/146675535-6ac3ee0e-4ecf-4f70-8fe7-97c160e0c007.png)

**Comment by hartontw** [comment]
The css selectors probably have changed. I will try to fix it soon.

**Comment by hartontw** [comment]
Fixed 15f4def6982994f2cc6ef36bee673243da30ea3a

**Comment by JasonBenfrin** [comment]
> Fixed [15f4def](https://github.com/hartontw/aternosAPI/commit/15f4def6982994f2cc6ef36bee673243da30ea3a)

Wow! It worked! Thanks for fixing it!
